FROM bitnami/discourse:alpine

WORKDIR /opt/bitnami/discourse
ENV RAILS_ENV="production"

# Add requirements and install application
RUN set -ex; \
    bundle exec rake plugin:install[https://github.com/jonmbake/discourse-ldap-auth]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-adplugin]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-affiliate]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-akismet]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-auto-deactivate]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-bbcode]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-bbcode-color]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-cakeday]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-canned-replies]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-characters-required]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-chat-integration]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-checklist]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-data-explorer]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-fingerprint]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-footnote]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-graphviz]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-math]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-matomo-analytics]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-oauth2-basic]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-patreon]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-plugin-linkedin-auth]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-push-notifications]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-saved-searches]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-signatures]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-sitemap]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-staff-notes]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-tooltips]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-user-card-badges]; \
    bundle exec rake plugin:install[https://github.com/discourse/discourse-voting]

# TODO Add https://github.com/discourse/discourse-assign
# TODO Add https://github.com/discourse/discourse-code-review
# TODO Add https://github.com/discourse/discourse-saml
# TODO Add https://github.com/discourse/discourse-solved
# FIXME Add https://github.com/discourse/discourse-styleguide when https://meta.discourse.org/t/discourse-styleguide-plugin-fails/168027

# Arguments to label built container
ARG VCS_REF
ARG BUILD_DATE
ARG VERSION=%%VERSION%%

# Keep track of image version
RUN set -ex; \
    mkdir -p '/app/src'; \
    echo "${VERSION} ${VCS_REF} ${BUILD_DATE}" > '/app/src/.docker-version'

# Container labels (http://label-schema.org/)
# Container annotations (https://github.com/opencontainers/image-spec)
LABEL maintainer="Monogramm maintainers <opensource at monogramm dot io>" \
      product="Discourse" \
      version=$VERSION \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url="https://github.com/Monogramm/docker-bitnami-discourse" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name="Discourse" \
      org.label-schema.description="The next-generation community forum platform." \
      org.label-schema.url="https://www.discourse.org/" \
      org.label-schema.vendor="Civilized Discourse Construction Kit, Inc." \
      org.label-schema.version=$VERSION \
      org.label-schema.schema-version="1.0" \
      org.opencontainers.image.revision=$VCS_REF \
      org.opencontainers.image.source="https://github.com/Monogramm/docker-bitnami-discourse" \
      org.opencontainers.image.created=$BUILD_DATE \
      org.opencontainers.image.title="Discourse" \
      org.opencontainers.image.description="The next-generation community forum platform." \
      org.opencontainers.image.url="https://www.discourse.org/" \
      org.opencontainers.image.vendor="Civilized Discourse Construction Kit, Inc." \
      org.opencontainers.image.version=$VERSION \
      org.opencontainers.image.authors="Monogramm maintainers <opensource at monogramm dot io>"
